openapi: 3.0.0
info:
  title: Organization API
  description: API for managing organizations.
  version: 1.0.0
servers:
  - url: http://localhost:3000/api/organizations
    description: Local server

paths:
  /:
    get:
      summary: Retrieve a list of all organizations.
      description: |
        Fetches all organizations. Requires the user to be authenticated and authorized with the `SUPERADMIN` role.
      security:
        - bearerAuth: []
      tags:
        - Organizations
      responses:
        '200':
          description: A list of organizations.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    name:
                      type: string
                      example: Example Organization
                    domain:
                      type: string
                      example: example.com
        '401':
          description: Unauthorized - Invalid or missing authentication token.
        '403':
          description: Forbidden - User lacks the required permissions.
        '500':
          description: Internal Server Error.
    post:
      summary: Create a new organization.
      description: |
        Creates a new organization. Requires the user to be authenticated.
        - SUPERADMIN users can create any organization.
        - Non-SUPERADMIN users can only create organizations under their domain.
      security:
        - bearerAuth: []
      tags:
        - Organizations
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Name of the organization.
                  example: New Organization
                domain:
                  type: string
                  description: Domain of the organization.
                  example: newdomain.com
              required:
                - name
                - domain
      responses:
        '201':
          description: Organization created successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 2
                  name:
                    type: string
                    example: New Organization
                  domain:
                    type: string
                    example: newdomain.com
        '401':
          description: Unauthorized - Invalid or missing authentication token.
        '403':
          description: Forbidden - Users can only create organizations under their domain if not SUPERADMIN.
        '500':
          description: Internal Server Error.

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Organization:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        domain:
          type: string
