version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth_awakens
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'

  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgres://user:password@localhost:5432/auth_awakens
      REDIS_URL: redis://redis:6379
      JWT_SECRET: supersecretkey
      RUN_MIGRATIONS: 'true'
    depends_on:
      - db
      - redis
    command: ['sh', '-c', 'npm run migrate up && node src/server.js']

volumes:
  postgres_data:
